/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ASpin: typeof import('ant-design-vue/es')['Spin']
    Button: typeof import('./src/components/ui/Button.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Highlights: typeof import('./src/components/Highlights.vue')['default']
    IconBillCheck: typeof import('./src/components/icons/IconBillCheck.vue')['default']
    IconGithub: typeof import('./src/components/icons/IconGithub.vue')['default']
    IconHeart: typeof import('./src/components/icons/IconHeart.vue')['default']
    IconMagicStick: typeof import('./src/components/icons/IconMagicStick.vue')['default']
    IconPalette: typeof import('./src/components/icons/IconPalette.vue')['default']
    IconTelegram: typeof import('./src/components/icons/IconTelegram.vue')['default']
    IconTwitch: typeof import('./src/components/icons/IconTwitch.vue')['default']
    IconValory: typeof import('./src/components/icons/IconValory.vue')['default']
    IconValoryBG: typeof import('./src/components/icons/IconValoryBG.vue')['default']
    Input: typeof import('./src/components/ui/Input.vue')['default']
    LanguageSwitcher: typeof import('./src/components/ui/LanguageSwitcher.vue')['default']
    Overlay: typeof import('./src/components/Overlay.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Switch: typeof import('./src/components/ui/Switch.vue')['default']
  }
}
