/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ASpin: (typeof import('ant-design-vue/es'))['Spin']
    Button: (typeof import('./src/components/ui/ButtonUI.vue'))['default']
    ColorPicker: (typeof import('./src/components/ui/ColorPicker.vue'))['default']
    DropdownMenu: (typeof import('./src/components/ui/DropdownMenu.vue'))['default']
    Footer: (typeof import('./src/components/Footer.vue'))['default']
    FooterItem: (typeof import('./src/components/FooterItem.vue'))['default']
    Highlights: (typeof import('./src/components/Highlights.vue'))['default']
    HighlightsItem: (typeof import('./src/components/HighlightsItem.vue'))['default']
    IconBillCheck: (typeof import('./src/components/icons/IconBillCheck.vue'))['default']
    IconClose: (typeof import('./src/components/icons/IconClose.vue'))['default']
    IconConfiguration: (typeof import('./src/components/icons/IconConfiguration.vue'))['default']
    IconGithub: (typeof import('./src/components/icons/IconGithub.vue'))['default']
    IconHeart: (typeof import('./src/components/icons/IconHeart.vue'))['default']
    IconLoading: (typeof import('./src/components/icons/IconLoading.vue'))['default']
    IconMagicStick: (typeof import('./src/components/icons/IconMagicStick.vue'))['default']
    IconPalette: (typeof import('./src/components/icons/IconPalette.vue'))['default']
    IconProfile: (typeof import('./src/components/icons/IconProfileEdit.vue'))['default']
    IconProfileEdit: (typeof import('./src/components/icons/IconProfileEdit.vue'))['default']
    IconTelegram: (typeof import('./src/components/icons/IconTelegram.vue'))['default']
    IconTwitch: (typeof import('./src/components/icons/IconTwitch.vue'))['default']
    IconValory: (typeof import('./src/components/icons/IconValory.vue'))['default']
    IconValoryBG: (typeof import('./src/components/icons/IconValoryBG.vue'))['default']
    Input: (typeof import('./src/components/ui/InputUI.vue'))['default']
    LanguageSwitcher: (typeof import('./src/components/ui/LanguageSwitcher.vue'))['default']
    Modal: (typeof import('./src/components/ui/ModalWindow.vue'))['default']
    Overlay: (typeof import('./src/components/Overlay.vue'))['default']
    OverlayItem: (typeof import('./src/components/OverlayItem.vue'))['default']
    RouterLink: (typeof import('vue-router'))['RouterLink']
    RouterView: (typeof import('vue-router'))['RouterView']
    Switch: (typeof import('./src/components/ui/SwitchUI.vue'))['default']
    UiButton: (typeof import('./src/components/ui/uiButton.vue'))['default']
    UiColorPicker: (typeof import('./src/components/ui/uiColorPicker.vue'))['default']
    UiInput: (typeof import('./src/components/ui/uiInput.vue'))['default']
    UiLanguageSwitcher: (typeof import('./src/components/ui/uiLanguageSwitcher.vue'))['default']
    UiModal: (typeof import('./src/components/ui/uiModal.vue'))['default']
    UiSwitch: (typeof import('./src/components/ui/uiSwitch.vue'))['default']
  }
}
